### ISSUE TITLE
EPG Days Above 7 Issue

### ISSUE THREAD

**Issue by eracknaphobia** [eracknaphobia/service.psvue.epg#22]
If the epg days setting is set above 7 days it fills the database and xml files with blank data.

**Comment by DiR3Wolf** [comment]
It is possible to restrain the setting to a list option, so people would cycle between numbers 1 through 7, instead of typing the number of days?

**Comment by eracknaphobia** [comment]
Yeah, the [slider](https://kodi.wiki/view/Add-on_settings#type.3D.22slider.22) object would work nicely for that.

**Comment by snoopyjoe** [comment]
I'll push my code to the master later today, but that's exactly what I did is make the setting a slider from 1-8.

**Comment by DiR3Wolf** [comment]
Thanks snoop.

@eracknaphobia   Another thought out loud...when EPG service is tested enough deeming it reliable and stable, would it be a good idea to merge the code with PS Vue addon, since the service is exclusive to this addon? That way, only one userdata folder to look up files, one settings page to control all PS Vue related stuff.

**Comment by eracknaphobia** [comment]
@snoopyjoe Should the slider stop at 7? I ran it with 8 days and can only got to 7am next friday (current time here 11:30 am Friday).

**Comment by eracknaphobia** [comment]
This issue was resolved in this pull request.
#27
